CREATE TABLE IF NOT EXISTS USER (
  id INT NOT NULL AUTO_INCREMENT,
  userName varchar(20) NOT NULL UNIQUE,
  password varchar(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ACCOUNT (
  id INT NOT NULL AUTO_INCREMENT,
  amount DECIMAL NOT NULL DEFAULT 0.0,
  bankName varchar(20) NOT NULL,
  user_id INT,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);